# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='error.proto',
  package='algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel',
  syntax='proto3',
  serialized_options=b'H\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x65rror.proto\x12Yalgorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel\"\xd9\x03\n\x05\x45rror\x12w\n\x06\x64omain\x18\x01 \x01(\x0e\x32g.algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error.Domain\x12s\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x65.algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error.Code\x12\x10\n\x08message_\x18\x03 \x01(\t\"Q\n\x06\x44omain\x12\x0f\n\x0b\x44OMAIN_NONE\x10\x00\x12\x12\n\x0e\x44OMAIN_UNKNOWN\x10\x01\x12\x0f\n\x0b\x44OMAIN_USER\x10\x02\x12\x11\n\rDOMAIN_SYSTEM\x10\x03\"}\n\x04\x43ode\x12\r\n\tCODE_NONE\x10\x00\x12\x10\n\x0c\x43ODE_UNKNOWN\x10\x01\x12\x14\n\x10\x43ODE_VALUE_ERROR\x10\x02\x12\x16\n\x12\x43ODE_RUNTIME_ERROR\x10\x03\x12\x11\n\rCODE_IO_ERROR\x10\x04\x12\x13\n\x0f\x43ODE_TYPE_ERROR\x10\x05\x42\x02H\x01\x62\x06proto3'
)



_ERROR_DOMAIN = _descriptor.EnumDescriptor(
  name='Domain',
  full_name='algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error.Domain',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOMAIN_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOMAIN_UNKNOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOMAIN_USER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOMAIN_SYSTEM', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=372,
  serialized_end=453,
)
_sym_db.RegisterEnumDescriptor(_ERROR_DOMAIN)

_ERROR_CODE = _descriptor.EnumDescriptor(
  name='Code',
  full_name='algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error.Code',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CODE_NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODE_UNKNOWN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODE_VALUE_ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODE_RUNTIME_ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODE_IO_ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CODE_TYPE_ERROR', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=455,
  serialized_end=580,
)
_sym_db.RegisterEnumDescriptor(_ERROR_CODE)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error.domain', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error.code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message_', full_name='algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error.message_', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ERROR_DOMAIN,
    _ERROR_CODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=580,
)

_ERROR.fields_by_name['domain'].enum_type = _ERROR_DOMAIN
_ERROR.fields_by_name['code'].enum_type = _ERROR_CODE
_ERROR_DOMAIN.containing_type = _ERROR
_ERROR_CODE.containing_type = _ERROR
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'error_pb2'
  # @@protoc_insertion_point(class_scope:algorithm_engineering.beggar_algorithm_service_system.algorithm_service_scheduling_kernel.Error)
  })
_sym_db.RegisterMessage(Error)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
